language: vi

pipeline:
<<<<<<< HEAD
    - name: WhitespaceTokenizer
      intent_split_symbol: "_"
=======
    # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
    # # If you'd like to customize it, uncomment and adjust the pipeline.
    # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
    #- name: WhitespaceTokenizer
    #  intent_split_symbol: "_"
    - name: VietnameseTokenizer
>>>>>>> cbbd2074c78dfafd14588a2744389978fdcf7208
    - name: RegexFeaturizer
    - name: LexicalSyntacticFeaturizer
    - name: DIETClassifier
    - name: CountVectorsFeaturizer
    - name: CountVectorsFeaturizer
      analyzer: char_wb
      min_ngram: 1
      max_ngram: 4
    - name: DIETClassifier
      epochs: 100
      constrain_similarities: true
    - name: EntitySynonymMapper
    - name: ResponseSelector
      epochs: 100
    - name: FallbackClassifier
      threshold: 0.7
    - name: RegexEntityExtractor # tìm kiếm giang vien trong look up table
      use_lookup_tables: true

policies:
    - name: VietnameseTokenizer
    - name: MemoizationPolicy
    - name: HFTransformersNLP
      model_weights: "vinai/phobert-base"
      model_name: "phobert"
    - name: LanguageModelTokenizer
    - name: LanguageModelFeaturizer
    - name: RulePolicy
      core_fallback_threshold: 0.4
      core_fallback_action_name: "action_default_fallback"
      enable_fallback_prediction: True
    - name: UnexpecTEDIntentPolicy
      max_history: 5
      epochs: 100
    - name: TEDPolicy
      max_history: 5
      epochs: 100
      constrain_similarities: true
